### ISSUE TITLE
Support more algorithms on KittenBlue.JWK.from_compact/1

### ISSUE THREAD

**Issue by enerick** [ritou/elixir-kitten-blue#17]
KittenBlue.JWK.from_compact/1 currently supports only limited algorithms.
https://github.com/ritou/elixir-kitten-blue/blob/ad0dd94975b50de5a19ffc8419d49a74496f819d/lib/kitten_blue/jwk.ex#L198

It would be nice to support more algorithms like EC256, Ed25519, etc.

**Comment by ritou** [comment]
It will be changed to...

* from_compact
  * key is map: from_map
  * alg in octet: from_oct
  * others: from_pem
* to_compact
  * use_map in opts: to_map
  * alg in octet: to_oct
  * others: to_pem
